openapi: 3.0.3
info:
  title: MCP Microsoft 365 API
  version: 1.0.0
  description: |
    Modular API for accessing Microsoft 365 mail, calendar, and files. Designed for LLM and agent integration.
servers:
  - url: http://localhost:3000/api/v1
paths:
  /query:
    post:
      summary: Submit a natural language query
      description: NLP-powered query endpoint for Microsoft 365 data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The user's natural language question
                context:
                  type: object
                  description: Conversation context (optional)
      responses:
        '200':
          description: Query response
  /mail:
    get:
      summary: Get mail from inbox
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: Number of messages to fetch
        - in: query
          name: filter
          schema:
            type: string
          description: Filter string
      responses:
        '200':
          description: List of mail messages
  /mail/send:
    post:
      summary: Send an email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                to:
                  oneOf:
                    - type: string
                    - type: array
                      items:
                        type: string
                  description: Recipient email address(es)
                subject:
                  type: string
                  description: Email subject
                body:
                  type: string
                  description: Email body
      responses:
        '200':
          description: Send mail result
  /calendar:
    get:
      summary: Get calendar events
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: Number of events to fetch
        - in: query
          name: filter
          schema:
            type: string
          description: Filter string
      responses:
        '200':
          description: List of calendar events
  /calendar/create:
    post:
      summary: Create a calendar event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subject:
                  type: string
                  description: Event subject
                start:
                  type: object
                  properties:
                    dateTime:
                      type: string
                      format: date-time
                      description: Start time (ISO 8601)
                    timeZone:
                      type: string
                      description: Time zone
                end:
                  type: object
                  properties:
                    dateTime:
                      type: string
                      format: date-time
                      description: End time (ISO 8601)
                    timeZone:
                      type: string
                      description: Time zone
      responses:
        '200':
          description: Calendar event created
  /files:
    get:
      summary: List files
      parameters:
        - in: query
          name: parentId
          schema:
            type: string
          description: Parent folder ID (optional)
      responses:
        '200':
          description: List of files
  /files/upload:
    post:
      summary: Upload a file
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: File name
                content:
                  type: string
                  description: File content (base64 or plain text)
      responses:
        '200':
          description: Upload result
components: {}
